version: '3'

services:
  web2:
    build: .
    command: ../delivery_init.sh
    environment:
        APP_LAUNCH_SITE: docker_debug
    container_name: 'delivery'
    restart: always
    volumes:
      - .:/code
    expose:
       - "84"
    ports:
       - "84:84"
