version: '3'

services:
  web2:
    build: .
    command: ../delivery_init.sh
    environment:
        APP_LAUNCH_SITE: docker
    container_name: 'delivery'
    restart: always
    volumes:
      - .:/code
    expose:
       - 8084

  nginx2:
    container_name: 'srv2'
    restart: always
    image: nginx:latest
    depends_on: 
      - web2
    ports:
      - 84:80
    volumes:
      - ./nginx:/etc/nginx/conf.d #папка для конфигурации nginx
      - ./delivery/static:/srv/www/static/ #статика приложения delivery2
      - ./delivery/media:/srv/www/media/ #загружнные картинки приложения delivery2
      - ./logs:/srv/www/logs/ # удаляется папка в контейнере и заменяется на папку их хоста, логи nginx
