version: '3'

services:
  web2:
    build: .
    command: gunicorn -b 0.0.0.0:8000 delivery.wsgi:application
    environment:
        APP_LAUNCH_SITE: docker
    container_name: 'app1'
    restart: always
    volumes:
      - .:/code
    expose:
       - "84"
    ports:
       - "84:8000"