# Generated by Django 3.0.5 on 2020-04-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блюда')),
                ('ingredients', models.CharField(max_length=500, verbose_name='Состав блюда')),
                ('price', models.IntegerField(verbose_name='Цена блюда')),
                ('image', models.ImageField(blank=True, upload_to='images/dishes/%Y/%m/%d/', verbose_name='Изображение ресторана')),
            ],
            options={
                'verbose_name': 'Блюдо',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название ресторана')),
                ('delivery_time', models.IntegerField(verbose_name='Время доставки')),
                ('rating', models.IntegerField(verbose_name='Рейтинг ресторана')),
                ('price_level', models.CharField(max_length=20, verbose_name='Уровень цен')),
                ('category', models.CharField(max_length=100, verbose_name='Категория ресторана')),
                ('image', models.ImageField(blank=True, upload_to='images/restaurants/%Y/%m/%d/', verbose_name='Изображение ресторана')),
                ('menu', models.ManyToManyField(blank=True, null=True, to='delivery_app.Dish')),
            ],
            options={
                'verbose_name': 'Ресторан',
            },
        ),
    ]
