# Generated by Django 3.0.5 on 2020-04-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0002_auto_20200412_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Ресторан', 'verbose_name_plural': 'Рестораны'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/dishes/%Y/%m/%d/', verbose_name='Изображение блюда'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.TextField(verbose_name='Состав блюда'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='menu',
            field=models.ManyToManyField(blank=True, to='delivery_app.Dish'),
        ),
    ]
