# Generated by Django 3.0.5 on 2020-04-18 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0005_auto_20200418_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='delivery_app.Restaurant', verbose_name='Ресторан'),
        ),
    ]
