# Generated by Django 3.0.5 on 2021-03-07 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0006_auto_20200418_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promo_text', models.CharField(max_length=500, verbose_name='Текст промо')),
                ('promo_color', models.CharField(max_length=10, verbose_name='Цвет подложки промо')),
                ('promo_img', models.ImageField(blank=True, upload_to='images/promo/', verbose_name='Картинка промо (png)')),
            ],
            options={
                'verbose_name': 'Промо постер',
                'verbose_name_plural': 'Промо постеры',
            },
        ),
    ]
