# Generated by Django 3.0.5 on 2021-03-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0007_promobox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promobox',
            name='promo_text',
            field=models.TextField(verbose_name='Текст промо'),
        ),
    ]
