# Generated by Django 3.0.5 on 2021-03-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0008_auto_20210307_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promobox',
            name='promo_color',
            field=models.CharField(max_length=100, verbose_name='Цвет подложки промо'),
        ),
    ]
